version: '3.7'

services:
  cnd:
    container_name: cnd-app
    image: registry.gitlab.com/sisaudcon/saam-api-cnd:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  bd-cnd:
    container_name: cnd-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5541:5432
    volumes:
      - postgres_cnd_data:/var/lib/postgresql/data

  frontend:
    container_name: cnd-frontend
    build: ../cnd-certidoes-monitor-14  # Caminho para Dockerfile frontend
    depends_on:
      - cnd
    # Não expõe porta do frontend diretamente, nginx serve frontend

  nginx:
    image: nginx:alpine
    container_name: cnd-nginx
    ports:
      - 3000:80  # acessa frontend+proxy no host:3000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../cnd-certidoes-monitor-14/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - cnd

  watchtower:
    container_name: cnd-watchtower
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config-app.json:/config.json:ro
    command: --http-api-update --scope=cnd
    environment:
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_HTTP_API_TOKEN}
      WATCHTOWER_REGISTRY_AUTH: "true"
    ports:
      - 8084:8080
    labels:
      - "com.centurylinklabs.watchtower.scope=cnd"

volumes:
  postgres_cnd_data:
